#Configuraciones b�sicas
spring.application.name=ministerio

#Configuraciones de seguridad
#spring.security.user.name=${SS_USER}
#spring.security.user.password=${SS_PASSWORD}
spring.security.user.name=admin
spring.security.user.password=1234

#Configuraciones de BD
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=${BD_URL}
#spring.datasource.username=${BD_USERNAME}
#spring.datasource.password=${BD_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/pps_sistema
spring.datasource.username=postgres
spring.datasource.password=1234

#Configuraciones de JWT
spring.jwt.private.key=admin
spring.jwt.user.generator=1234